maintainer: "Spark 1"

general_params:
  regex_file: "config/regex.yaml"
  report_file: "n0s1_report.json"
  post_comment: false
  skip_comment: false
  show_matched_secret_on_logs: false
  report_format: "n0s1"
  timeout: null
  limit: null
  insecure: false

comment_params:
  bot_name: "n0s1 bot"
  message_template: "Hello! I'm {bot_name}, and I'm here to assist you in preventing data leaks.\nI apologize for being nosy, but it appears that there may have been potentially sensitive data posted here in the past.\n\n.\nHere are the details:\n{finding_info}\n.\n\nIf you can verify that this is indeed an actual data leak, please take the necessary steps to rotate the credentials and remove any previously shared sensitive information.\nFor future reference, consider using {secret_manager} whenever you need to share credentials or any other sensitive data securely.\nIf you require further assistance, please don't hesitate to reach out to us at {contact_help}\n\n{label}"
  secret_manager: "a secret manager tool"
  contact_help: "contact@spark1.us"
  label: "n0s1bot_auto_comment_e869dd5fa15ca0749a350aac758c7f56f56ad9be1"

